---
- hosts: dev
  tasks:
  - name: pinging
    ping:
  - name: coping file
    copy:
      src: k8s/
      dest: /home/tafara/k8s/
      
  - name: deployment1
    cmd: kubectl apply -f k8s/deployment1.yaml && kubectl apply -f k8s/services.yaml

  #- name: deploying k8s deployment
  #  k8s:
  #    state: present
  #    src: k8s/deployment1.yaml
  
  #- name: deploying K8s service
  #  k8s:
  #    state: present
  #    src: /k8s/services.yaml
